### PR TITLE
Add value to interface

### PR DESCRIPTION
**Pull request by d-xo**
Allows users to specify the value that must be provided for the `delegatecall` in exec.

### CODE REVIEW

**Comment by livnev** [comment]
Just want to point out that the decision of whether `exec` should use `CALL` or keep `DELEGATECALL` is very relevant to this part IMO.

**Comment by nmushegian** [comment]
One thing is for sure, we can't let a bunch different versions of almost the same very sensitive/tricky code exist (proxy/pause/exec etc)

We need distinct words for exec-as-in-call and exec-as-in-delegatecall. Make two (deliberately incompatible?) mixins.

**Comment by asymmetric** [comment]
@xwvvvvwx Do you want to rebase this? AFAICT we want to proceed with this independently of the choice between `CALL`/`DELEGATECALL`, amirite?

**Comment by d-xo** [comment]
@asymmetric yes I would like to move forward with this change, thanks for the nudge. rebased.

@livnev could you outline how you think `call` vs `delegatecall` interacts with this change, as I remember from our discussions previously, you had some UX concerns?

@nmushegian I think your comment belongs in the discussion on https://github.com/dapphub/ds-pause/issues/15.

**Comment by d-xo** [comment]
After spending some more time thinking about this, I'm not going to merge this because it's not required for Maker governance, and I can't come up with a clear motivating use case.

Will add it to the interface if we decide it's required in the future.

**Pull request closed without merging**
